import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'beeven' at '12/20/16 12:53 AM' with Gradle 3.2.1
 *
 * @author beeven, @date 12/20/16 12:53 AM
 */
public class MkCertTest {
    @Test public void testSomeLibraryMethod() {
        MkCert classUnderTest = new MkCert();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
