/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'beeven' at '12/20/16 12:53 AM' with Gradle 3.2.1
 *
 * @author beeven, @date 12/20/16 12:53 AM
 */

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.security.Key;
 
import org.bouncycastle.util.io.pem.PemObject;
import org.bouncycastle.util.io.pem.PemReader;
import org.bouncycastle.util.io.pem.PemWriter;

public class MkCert {
    public boolean someLibraryMethod() {
        return true;
    }

    public void generateKeyPair() {
        
    }

    public static void main(String[] args){

        System.out.println("Hello world!");
    }
}
